title: Ravi Thothadri
#logo: docs/assets/headshot.png
description: Data Scientist | 2X AWS Certified ML Specialty, Cloud Practitioner | Wealth Management
#show_downloads: true
theme: jekyll-theme-minimal
